server:
  port: 3000

database:
  connectionString : "postgresql://abdelrahman:inkP0FcTDCTQ4cBxYmXLDQ@free-tier13.aws-eu-central-1.cockroachlabs.cloud:26257/cloned-grebe-2605.defaultdb?sslmode=verify-full"

kafka:
  URL : "localhost:9092"
  topic : "topic_0"
  maxBytes: 30